INSERT IGNORE INTO mascots (name, slug, icon_path) VALUES
('Bear',        'bear',        '/images/teams/mascots/bear.png'),
('Beaver',      'beaver',      '/images/teams/mascots/beaver.png'),
('Blue Devil',  'blue-devil',  '/images/teams/mascots/blue-devil.png'),
('Bob',         'bob',         '/images/teams/mascots/bob.png'),
('Bobcat',      'bobcat',      '/images/teams/mascots/bobcat.png'),
('Bull',        'bull',        '/images/teams/mascots/bull.png'),
('Bull Dog',    'bull-dog',    '/images/teams/mascots/bull-dog.png'),
('Captain',     'captain',     '/images/teams/mascots/captain.png'),
('Cardinal',    'cardinal',    '/images/teams/mascots/cardinal.png'),
('Cat',         'cat',         '/images/teams/mascots/cat.png'),
('Croc',        'croc',        '/images/teams/mascots/croc.png'),
('Eagle',       'eagle',       '/images/teams/mascots/eagle.png'),
('Elephant',    'elephant',    '/images/teams/mascots/elephant.png'),
('Hawk',        'hawk',        '/images/teams/mascots/hawk.png'),
('Horse',       'horse',       '/images/teams/mascots/horse.png'),
('Husky',       'husky',       '/images/teams/mascots/husky.png'),
('Jay Hawk',    'jay-hawk',    '/images/teams/mascots/jay-hawk.png'),
('Knight',      'knight',      '/images/teams/mascots/knight.png'),
('Leprechaun',  'leprechaun',  '/images/teams/mascots/leprechaun.png'),
('Lion',        'lion',        '/images/teams/mascots/lion.png'),
('Lioness',     'lioness',     '/images/teams/mascots/lioness.png'),
('Owl',         'owl',         '/images/teams/mascots/owl.png'),
('Police',      'police',      '/images/teams/mascots/police.png'),
('Ram',         'ram',         '/images/teams/mascots/ram.png'),
('Red Devil',   'red-devil',   '/images/teams/mascots/red-devil.png'),
('Tiger',       'tiger',       '/images/teams/mascots/tiger.png'),
('Turtle',      'turtle',      '/images/teams/mascots/turtle.png'),
('Wolf',        'wolf',        '/images/teams/mascots/wolf.png');
